src/task_12/api/app/app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("mlak/", include("mlak.urls")),
    path("admin/", admin.site.urls),
]

src/task_12/api/app/mlak/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView


app_name = "mlak"


urlpatterns = [
    path("", views.BooksView.as_view(), name="index"),
    path(
        "login/",
        LoginView.as_view(
            template_name="mlak/login.html",
            next_page="mlak:index",
            redirect_authenticated_user=True,
                ),
        name="login",
            ),
    path(
        "logout/",
        LogoutView.as_view(next_page="mlak:index"),
        name="logout",
            ),
    path(
        "signup/",
        views.SignUpView.as_view(),
        name="signup"
            ),
        ]

src/task_12/api/app/mlak/models.py
from django.db import models

class Books(models.Model):
    """Books model"""
    title = models.TextField()
    author = models.TextField()
    genre = models.TextField()
    description = models.TextField()
    isbn = models.BigIntegerField()
    image = models.TextField()
    published = models.DateTimeField()
    publisher = models.TextField()

    def __str__(self):
        return f"Author: {self.author} | title: {self.title}"

src/task_12/api/app/mlak/views.py
from django.views import View
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from .models import Books


def index(request):
    return render(request, "mlak/index.html")

class BooksView(View):
    """Books view
    """

    def get(self, request):
        """Get all books"""
        books = Books.objects.all().values()

        return render(
            request,
            "mlak/index.html",
            {"books": books, },
                )


class SignUpView(View):
    """Signup view
    """
    def get(self, request):
        """Render form
        """
        return render(
            request,
            "mlap/sign.html",
            {"form": UserCreationForm(), },
                )


def post(self, request):
    """Get signup
    """
    form = UserCreationForm(request.POST)

    if form.is_valid():
        form.save()

        username = form.data["username"]
        password = form.data["password1"]

        user = authenticate(
                request,
                username=username,
                password=password,
                    )

        if user:
            login(request, user)

        return redirect("/")

    return render(
        request,
        "giffy_app/sign.html",
        {"form": form, },
            )

src/task_12/api/app/mlak/templates/mlak/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Mlak</title>
    </head>

    <body>
        <a href="/">Main</a>
        {% if user.is_authenticated %}
            | <a href="{% url 'mlak:logout' %}">Logout</a>
        {% else %}
            | <a href="{% url 'mlak:login' %}">Login</a>
            | <a href="{% url 'mlak:signup' %}">Signup</a>
        {% endif %}
    {% block content %}
    {% endblock content %}
    </body>

</html>

src/task_12/api/app/mlak/templates/mlak/book.html
<p>
    Author: <b>{{ book.author }} </b>
    Title: <b>{{ book.title }} </b>
    | {{ book.genre }}
    | {{ book.description }}
    | {{ book.isbn }}
    | {{ book.image }}
    | {{ book.isbn }}
    | {{ book.published }}
    | {{ book.publisher }}
</p>

src/task_12/api/app/mlak/templates/mlak/index.html
{% extends "mlak/base.html" %}

{% block content %}
<main>
    <div>
        {% if user.is_authenticated %}
            <h1>Books:</h1>
            {% for book in books %}
                {% include 'mlak/book.html' %}
            {% endfor%}
        {% else %}
            <h3>SignUp to read a books summary.</h3>
        {% endif %}
    </div>

</main>
{% endblock content %}

src/task_12/api/app/mlak/templates/mlak/login.html
{% extends "mlak/base.html" %}

{% block content %}
<div>
  <h3>Login</h3>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit"/>
  </form>
</div>
{% endblock content %}

src/task_12/api/app/mlak/templates/mlak/sign.html
{% extends "mlap/base.html" %}

{% block content %}
<div>
  <h3>Sign up</h3>
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
  </form>
</div>
{% endblock content %}